### PR TITLE
firewall: remove magic numbers

### PR DESCRIPTION
**Pull request by greut**
8 and 128 are defined elsewhere already

### CODE REVIEW

**Comment by pierre-emmanuelJ** [comment]
Is it WIP?

**Comment by greut** [comment]
is it?

**Comment by greut** [comment]
looks like it :)

```console
% exo firewall add wide-open ping ping6
Add "ping" rule for "wide-open" ⠼                                                                                done!
Add "ping6" rule for "wide-open" ⠼                                                                                done!
failure Add "ping6" rule for "wide-open": API error ParamError 431 (CSErrorCode(0) 0): Invalid cidr for ICMPv6: 0.0.0.0/0
```

**Comment by greut** [comment]
```console
% exo firewall add wide-open ping ping6                                                                  
Add "ping" rule for "wide-open" ⠼                                                                                done!
Add "ping6" rule for "wide-open" ⠼                                                                                done!
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼
│  TYPE   │     SOURCE     │ PROTOCOL │         PORT          │ DESCRIPTION │                  ID                  │
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼
│ INGRESS │ CIDR ::/0      │ icmpv6   │ 128, 0 (Echo Request) │             │ 7ef4a317-4ce7-496a-93d6-9b0345eae0c7 │
│         │ CIDR 0.0.0.0/0 │ icmp     │ 8, 0 (Echo)           │             │ 4e82d7a2-061e-43d6-abde-5bae5c217a43 │
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼

% exo firewall add wide-open ping ping6 --ipv6
Add "ping" rule for "wide-open" ⠼                                                                                done!
Add "ping6" rule for "wide-open" ⠼                                                                                done!
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼
│  TYPE   │     SOURCE     │ PROTOCOL │         PORT          │ DESCRIPTION │                  ID                  │
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼
│ INGRESS │ CIDR ::/0      │ icmpv6   │ 128, 0 (Echo Request) │             │ e3a292d4-f5dd-4029-86f1-eb709875c56e │
│         │ CIDR 0.0.0.0/0 │ icmp     │ 8, 0 (Echo)           │             │ aa9aa86d-8b2d-41ba-a589-2ffc9e1e117b │
┼─────────┼────────────────┼──────────┼───────────────────────┼─────────────┼──────────────────────────────────────┼

```

**Pull request merged**
