### PR TITLE
firewall: check for CIDR or SG when adding a rule

### PR DESCRIPTION
**Pull request by falzm**
This change requires a CIDR or a Security Group to be specified when
adding a rule.

### CODE REVIEW

**Comment by jessicatoscani** [comment]
There is still a problem.
If protocol is not set, the new rule created is never what I was expecting

```
exo firewall add default --cidr 0.0.0.0/0 -P 8080 
┼──────────────────────────────────────┼─────────┼────────────────┼──────┼──────────┼─────────────┼
│                  ID                  │  TYPE   │     SOURCE     │ PORT │ PROTOCOL │ DESCRIPTION │
┼──────────────────────────────────────┼─────────┼────────────────┼──────┼──────────┼─────────────┼
│ 1aea8342-cd52-48fc-bf96-22d7c10661dd │ ingress │ CIDR 0.0.0.0/0 │ 0    │ all    
```

**Comment by falzm** [comment]
@jessicatoscani I think a sensible fix would be to return an error if `--port` is specified without `--protocol`, are you OK with this?

**Comment by jessicatoscani** [comment]
> @jessicatoscani I think a sensible fix would be to return an error if `--port` is specified without `--protocol`, are you OK with this?

Yes.

**Comment by jessicatoscani** [comment]
Not sure about the mandatory --cidr

**Comment by falzm** [comment]
> Not sure about the mandatory --cidr

It's not mandatory, but you either have to provide a CIDR or a Security Group.

**Comment by falzm** [comment]
> > @jessicatoscani I think a sensible fix would be to return an error if `--port` is specified without `--protocol`, are you OK with this?
> 
> Yes.

Fixed.

**Comment by jessicatoscani** [comment]
> > Not sure about the mandatory --cidr
> 
> It's not mandatory, but you either have to provide a CIDR or a Security Group.

Previous behaviour was fine:  add rule with  cidr = 0.0.0.0/0 when CIDR and SG were missing

**Comment by falzm** [comment]
My bad, I've reverted my original fix and only kept the check on the port/protocol: @jessicatoscani can you confirm it's OK now?

**Pull request merged**
