### PR TITLE
Add support for output formatting

### PR DESCRIPTION
**Pull request by falzm**
This change adds support for various output formatting methods, including:

* table (default)
* JSON
* free-form Go templates (a la `docker inspect`/`kubectl get`)

🚧 This is a prototype, implemented only on the `affinitygroup list`/`affinitygroup show` commands for now: if this implementation is validated, I'll apply it to all `list`/`show` commands. 

```console
# table (default)
$ ./exo -O table affinitygroup show ab-abcd-xyz1
┼──────────────┼───────────────────────────────────────────────────────┼
│ AB-ABCD-XYZ1 │                                                       │
┼──────────────┼───────────────────────────────────────────────────────┼
│ ID           │ b061b2c3-12eb-43e2-a066-389daa1cd525                  │
│ Name         │ ab-abcd-xyz1                                          │
│ Description  │ keep ab-abcd-xyz1 on different hyperv                 │
│ Instances    │                                                       │
│              │   ab-abcd006   1ffc2e78-a017-4bc8-be45-cc1700446c28   │
│              │   ab-abcd004   f2bd1007-35fd-427b-93b2-ebe41897064b   │
│              │   ab-abcd005   e3c51601-f7ee-4c10-bc77-ee24eac5412a   │
│              │                                                       │
┼──────────────┼───────────────────────────────────────────────────────┼

# JSON
$ ./exo -O json affinitygroup show ab-abcd-xyz1 | jq .
{
  "id": "b061b2c3-12eb-43e2-a066-389daa1cd525",
  "name": "ab-abcd-xyz1",
  "description": "keep ab-abcd-xyz1 on different hyperv",
  "instances": {
    "ab-abcd004": "f2bd1007-35fd-427b-93b2-ebe41897064b",
    "ab-abcd005": "e3c51601-f7ee-4c10-bc77-ee24eac5412a",
    "ab-abcd006": "1ffc2e78-a017-4bc8-be45-cc1700446c28"
  }
}

# template
$ ./exo -O text --output-template '{{.ID}}/{{.Name}}' affinitygroup show ab-abcd-xyz1
b061b2c3-12eb-43e2-a066-389daa1cd525/ab-abcd-xyz1
```

Implementation status:

- [x] affinitygroup list
- [x] affinitygroup show
- [x] config list
- [x] config show
- [x] dns list
- [x] dns show
- [x] eip list
- [x] eip show
- [x] firewall list
- [x] firewall show
- [x] kube list
- [x] privnet list
- [x] privnet show
- [x] runstatus incident list
- [x] runstatus incident show
- [x] runstatus list
- [x] runstatus maintenance list
- [x] runstatus maintenance show
- [x] runstatus service list
- [x] runstatus service show
- [x] runstatus show
- [x] snapshot list
- [x] sshkey list
- [x] template list
- [x] template show
- [x] vm list
- [x] vm show

### CODE REVIEW

**Comment by falzm** [comment]
[ch3451]

**Comment by bcachet** [comment]
I will be able to use JQ with output from EXO CLI :smiley:

**Comment by falzm** [comment]
Added list output support:

```console
$ ./exo -O table affinitygroup list
┼──────────────────────────────────────┼────────────────────────┼────────────────────────────────────────────────────────┼──────┼
│                  ID                  │          NAME          │                      DESCRIPTION                       │ SIZE │
┼──────────────────────────────────────┼────────────────────────┼────────────────────────────────────────────────────────┼──────┼
│ b061b2c3-12eb-43e2-a066-389daa1cd525 │ ab-opqr-xyz1           │ keep ab-opqr-xyz1 on different hyperv                  │ 3    │
│ 6d4ab1f2-70eb-4cdb-95a4-ba2b1c13b6d7 │ abcd-dfjndf-xyz1       │ keep all the workers on different hyperv               │ 5    │
│ ...                                                                                                                           │
│ b0842c52-a0be-4d6a-ab47-5f618e7b2e1e │ abcde-opqr-xyz1        │ XYZ1 abcde-opqr cluster anti affinity group            │ 7    │
│ edf882e5-8895-480c-b3ef-40d7f2771b1b │ abcde-abcdefgh-xyz1    │ XYZ1 abcde-abcdefgh anti affinity group                │ 3    │
┼──────────────────────────────────────┼────────────────────────┼────────────────────────────────────────────────────────┼──────┼

./exo -O json affinitygroup list | jq .
[
  {
    "ab": "b061b2c3-12eb-43e2-a066-389daa1cd525",
    "name": "ab-opqr-xyz1",
    "description": "keep ab-opqr-xyz1 on different hyperv",
    "size": 3
  },
  {
    "ab": "6d4ab1f2-70eb-4cdb-95a4-ba2b1c13b6d7",
    "name": "kube-worker-xyz1",
    "description": "keep all the workers on different hyperv",
    "size": 5
  },
  ...
  {
    "ab": "b0842c52-a0be-4d6a-ab47-5f618e7b2e1e",
    "name": "abcde-opqr-xyz1",
    "description": "XYZ1 abcde-opqr cluster anti affinity group",
    "size": 7
  },
  {
    "ab": "edf882e5-8895-480c-b3ef-40d7f2771b1b",
    "name": "abcde-abcdefgh-xyz1",
    "description": "XYZ1 abcde-abcdefgh anti affinity group",
    "size": 3
  }
]

$ ./exo -O template --output-template '{{.Size}} {{.Name}}' affinitygroup list | sort -nr
9 stuv-dfjndf-xyz1
8 abcde-ijklm-xyz1_2
8 abcde-ijklm-xyz1
8 abcde-ijklm-vie1_2
...
```

**Comment by falzm** [comment]
Added command template annotation auto-documentation:

```console
./exo affinitygroup list --help
This command lists existing Anti-Affinity Groups

Supported output template annotations: .ID, .Name, .Description, .Size

Usage:
  exo affinitygroup list [flags]

Aliases:
  list, ls

Flags:
  -h, --help   help for list

Global Flags:
  -C, --config string            Specify an alternate config file [env EXOSCALE_CONFIG]
  -O, --output-format string     Output format, can be table|json|template (default "table")
      --output-template string   Template to use if output format is "template"
  -A, --use-account string       Account to use in config file [env EXOSCALE_ACCOUNT]

$ ./exo affinitygroup show --help
This command shows an Anti-Affinity Group details

Supported output template annotations: .ID, .Name, .Description, .Instances

Usage:
  exo affinitygroup show <name | id> [flags]

Aliases:
  show, get

Flags:
  -h, --help   help for show

Global Flags:
  -C, --config string            Specify an alternate config file [env EXOSCALE_CONFIG]
  -O, --output-format string     Output format, can be table|json|template (default "table")
      --output-template string   Template to use if output format is "template"
  -A, --use-account string       Account to use in config file [env EXOSCALE_ACCOUNT]
```

**Comment by aarongroom** [comment]
Thanks @falzm, this is a great feature. 🥇 

It'd be nice if there was a `--plaintext` option of some kind.  It might be the same thing as the template option you've described depending how it's implemented.

Plaintext output (separated by tabs, for example), would play nicely with other UNIX utilities such as `awk(1)` and `wc(1)`, allowing easy chaining of commands together without having to write a separate API consumer program or pipe through `jq` first (`jq` is not installed by default on most systems).  Point 8 [in this post](https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46) provides a bit of an argument against using table borders.

The example output above in plaintext would look something like:

>ID\tName\tDescription\n1234\tmy-group\tmy description

That would facilitate easy pipelining with `awk -F'\t'`

Maybe the `--output-template` above could provide all the fields (with a separator such as tab) if no template is provided, and an `--output-plaintext` could alias that option?

I'd even go as far as making the plaintext option the default, but realize that would break existing workflows and might be worth getting more feedback first. 😸

**Comment by falzm** [comment]
Thank you @aarongroom for your feedback. Indeed a [TSV](https://en.wikipedia.org/wiki/Tab-separated_values)-like format would be a nice addition, however I'm not sure it would fit all commands' output as some of them have multiple "levels" of content – `exo affinitygroup show` illustrated above is a good example. Do you have a suggestion for this? We could restrict if for the `exo * list` commands, but I'd rather avoid making exceptions at this level...

**Comment by falzm** [comment]
@aarongroom would it be OK if I renamed the *template* output to *text*, and let the user shape the  output format with a preferred separator (e.g. `exo affinitygroup list -O text --output-template '{{.Name}}\t{{.Description}}'`) ?

**Comment by aarongroom** [comment]
@falz sounds good.  And in the absense of a specified template, it could maybe default to all fields separated by a tab.  Thanks again for the PR.

**Comment by falzm** [comment]
> And in the absense of a specified template, it could maybe default to all fields separated by a tab.

OK, I'll see if I can manage to do this with with nested content. Worst case scenario, I'll only display top-level content by default if no template is provided by the user.

**Comment by falzm** [comment]
Implementation status:

- [ ] affinitygroup list
- [ ] affinitygroup show
- [ ] config list
- [ ] config show
- [ ] dns list
- [ ] dns show
- [ ] eip list
- [ ] eip show
- [ ] firewall list
- [ ] firewall show
- [ ] kube list
- [ ] privnet list
- [ ] privnet show
- [ ] runstatus incident list
- [ ] runstatus incident show
- [ ] runstatus list
- [ ] runstatus maintenance list
- [ ] runstatus maintenance show
- [ ] runstatus service list
- [ ] runstatus service show
- [ ] runstatus show
- [ ] snapshot list
- [ ] sos list
- [ ] sshkey list
- [ ] template list
- [ ] template show
- [ ] vm list
- [ ] vm show

**Comment by falzm** [comment]
bcf4866 is for you @aarongroom ;)

```console
$ $ ./exo -A exoscale-ops dns show exoscale.com -O text --output-template '{{.RecordType}}' | sort | uniq -c | sort -nr
     19 CNAME
     13 MX
     11 A
      4 NS
      3 AAAA
      2 TXT
      1 SOA

$ ./exo -A exoscale-ops dns show exoscale.com -O text | awk -F '\t' '{print $4}' | sort | uniq -c | sort -nr
     19 CNAME
     13 MX
     11 A
      4 NS
      3 AAAA
      2 TXT
      1 SOA
```

**Comment by falzm** [comment]
Bonus feat. for @bcachet and @aarongroom: I've added a global `~/.exoscale/exoscale.toml` configuration setting `defaultOutputFormat` so you can persist your preferred output format without having to specify for every command (can be overridden with the `-O` flag) 😎

**Pull request merged**
