### PR TITLE
updateip to remove the dhcp lease

### PR DESCRIPTION
**Pull request by greut**
```console
# set
> exo vm updateip <vm> <privnet> --ip <ip>

# unset
> exo vm updateip <vm> <privnet>
```

Also, it adapts to the recent changes in the API

### CODE REVIEW

**Comment by pierre-emmanuelJ** [comment]
Nice Job 👍

**Comment by greut** [comment]
(rebased)

**Comment by greut** [comment]
- https://sos-ch-dk-2.exo.io/yoanyoan/cli_SNAPSHOT-6ad59bf_darwin_amd64.tar.gz
- https://sos-ch-dk-2.exo.io/yoanyoan/cli_SNAPSHOT-6ad59bf_linux_amd64.tar.gz

```
d2919eac131e9127256127105efec53bea26b18cc32cb66c0aacf2ebf6f402a8  cli_SNAPSHOT-6ad59bf_darwin_amd64.tar.gz
fcce726373bc6069245d2a726fe8d8ecd09e5b9321a3f63ee482e085fa486aef  cli_SNAPSHOT-6ad59bf_linux_amd64.tar.gz
```

**Comment by greut** [comment]
https://sos-ch-dk-2.exo.io/yoanyoan/cli_SNAPSHOT-e04248b02a52e530029a7d9f4c4478271bb687e4_darwin_amd64.tar.gz

bdc254c5b4caa98993537cb132fb287e6bced348ca29a50ef12723fa68a45522  cli_SNAPSHOT-e04248b02a52e530029a7d9f4c4478271bb687e4_darwin_amd64.tar.gz

https://sos-ch-dk-2.exo.io/yoanyoan/cli_SNAPSHOT-e04248b02a52e530029a7d9f4c4478271bb687e4_linux_amd64.tar.gz

057b94f9e67e27821eab114928d4d8e0977c7479672b346e288c8bb377f11914  cli_SNAPSHOT-e04248b02a52e530029a7d9f4c4478271bb687e4_linux_amd64.tar.gz

**Comment by pierre-emmanuelJ** [comment]
Great Job ! 👍 
image

**Pull request merged**
