### PR TITLE
kube: resolve exact k8s version

### PR DESCRIPTION
**Pull request by greut**
**Before**

```console
% exo lab kube create foo --version 1.11
```
| NAME |   IP ADDRESS    | SIZE  | VERSION |  STATE  |
|------|-----------------|-------|---------|---------|
| foo  | 159.100.241.221 | Small | 1.11    | Running |

```console
% exo lab kube create foo --version 1.11.1 
unable to find Kubernetes release for version "stable-1.11.1"
```

----

**Then**

```console
% exo lab kube create foo --kubernetes-version 1.11
```

| NAME |   IP ADDRESS    |  SIZE  | VERSION |  STATE  |
|------|-----------------|--------|---------|---------|
| foo  | 159.100.241.213 | Medium | 1.11.6  | Running |

```console
% exo lab kube create foo --kubernetes-version v1.11.1 --docker-version 18.03
```

| NAME |   IP ADDRESS    |  SIZE  | VERSION |  STATE  |
|------|-----------------|--------|---------|---------|
| foo  | 159.100.241.225 | Medium | 1.11.1 | Running |

```console
% exo ssh foo

$ docker version
Version:      18.03.1-ce
...

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", ...
```

Other changes:
- apt-mark hold docker-ce
- calico v3.4 (was v3.3)
- change tag name

### CODE REVIEW

**Comment by greut** [comment]
@falzm then I'd also remove the Kubernetes version flag.

**Comment by falzm** [comment]
> @falzm then I'd also remove the Kubernetes version flag.

Sure, let's do that – we can re-introduce this feature if users ask for it.

**Comment by greut** [comment]
@falzm alrighty then, I'll do this in this PR if you don't mind.

**Comment by falzm** [comment]
🚀 👍

**Comment by greut** [comment]
https://sos-ch-dk-2.exo.io/yoanyoan/exoscale-cli_SNAPSHOT-888783455f900823148b72f137ce199a1d0ba566_linux_amd64.tar.gz

**Pull request merged**
